## Institut des Algorithmes du Sénégal

## Cours 1 de Machine Learning

## 1. Some usefull libraries

## - Pandas

## - Numpy

## - Matplotlib

## - Seaborn

## - Scikit-learn

## Getting started with pandas

![image.png]()

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

## import pandas library

In [ ]:
import pandas as pd

Notice that we have written ‘as pd’ in the import statement above, this is how we alias imports in Python. Since it is difficult to write the compete term Pandas everywhere you use the library, you simply reference it by using the term ‘pd’. 


Pandas allow you to load data from various sources such as excel sheets, CSV(comma separated values) files, text files, and even SQL tables. Our data is in the form of a CSV file so we will use the following function to load our dataset.

## Create Dataframe

## DDéfinition d'un dataframe:

Un dataframe est une structure de données qui contient trois éléments fondamentaux ⁉

## - Des colonnes

## - Des index

## - Des données

## Pour créer un dataframe, on a besoin de deux choses :

## - Des vecteurs (list) de longueurs égales

## - La fonction Dataframe()

In [ ]:
import pandas as pd

data = {'Modules formation IAS': ["Python","MatLab","R","Machine learning","Deep learning"],
        "Nombre d'inscrits": [36,20,30,45,29]
        }
df = pd.DataFrame(data)

print(df)

  Modules formation IAS  Nombre d'inscrits
0                Python                 36
1                MatLab                 20
2                     R                 30
3      Machine learning                 45
4         Deep learning                 29

## Rread and manipulate dataframe

In [ ]:
world_power_data = pd.read_csv("World Energy Consumption.csv")

Let’s view what we have in the data.

In [ ]:
## 5 first rows of the DataFrame
world_power_data.head(7)

  iso_code      country  ...  wind_elec_per_capita  wind_energy_per_capita
0      AFG  Afghanistan  ...                   NaN                     NaN
1      AFG  Afghanistan  ...                   NaN                     NaN
2      AFG  Afghanistan  ...                   NaN                     NaN
3      AFG  Afghanistan  ...                   NaN                     NaN
4      AFG  Afghanistan  ...                   NaN                     NaN
5      AFG  Afghanistan  ...                   NaN                     NaN
6      AFG  Afghanistan  ...                   NaN                     NaN

[7 rows x 122 columns]

In [ ]:
## Get the shape of the dataframe

world_power_data.shape

(960, 122)

In [ ]:
world_power_data.head(3)

  iso_code      country  ...  wind_elec_per_capita  wind_energy_per_capita
0      AFG  Afghanistan  ...                   NaN                     NaN
1      AFG  Afghanistan  ...                   NaN                     NaN
2      AFG  Afghanistan  ...                   NaN                     NaN

[3 rows x 122 columns]

In [ ]:
## get infos from the dataframe

world_power_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Columns: 122 entries, iso_code to wind_energy_per_capita
dtypes: float64(119), int64(1), object(2)
memory usage: 915.1+ KB

In [ ]:
## Select dataframe by column (list(world_power_data.columns)[1:10])

#world_power_data[list(world_power_data.columns)[5:60]]

In [ ]:
## Remove specific datafrem from the file: for example, remove 2020 data

index_2020 = world_power_data[(world_power_data['year']==2020)].index
index_2020

Int64Index([800], dtype='int64')

In [ ]:
new_df = world_power_data.drop(index = index_2020, inplace = True)

In [ ]:
new_df

In [ ]:
## Reset the index of the dataframe
world_power_data.reset_index(inplace = True)

In [ ]:
world_power_data.head()

   index iso_code  ... wind_elec_per_capita  wind_energy_per_capita
0      0      AFG  ...                  NaN                     NaN
1      1      AFG  ...                  NaN                     NaN
2      2      AFG  ...                  NaN                     NaN
3      3      AFG  ...                  NaN                     NaN
4      4      AFG  ...                  NaN                     NaN

[5 rows x 123 columns]

In [ ]:
## Keep only focus countries

focus_countries = ["Algeria","Afghanistan","Angola","Australia"]

countriespower_data = world_power_data[(world_power_data['country'].isin(focus_countries))]

In [ ]:
print(countriespower_data)

     index iso_code  ... wind_elec_per_capita  wind_energy_per_capita
0        0      AFG  ...                  NaN                     NaN
1        1      AFG  ...                  NaN                     NaN
2        2      AFG  ...                  NaN                     NaN
3        3      AFG  ...                  NaN                     NaN
4        4      AFG  ...                  NaN                     NaN
..     ...      ...  ...                  ...                     ...
954    955      AUS  ...                  NaN                     NaN
955    956      AUS  ...                  NaN                     NaN
956    957      AUS  ...                  NaN                     NaN
957    958      AUS  ...                  NaN                     NaN
958    959      AUS  ...                  NaN                     NaN

[402 rows x 123 columns]

In [ ]:
world_power_data

     index iso_code  ... wind_elec_per_capita  wind_energy_per_capita
0        0      AFG  ...                  NaN                     NaN
1        1      AFG  ...                  NaN                     NaN
2        2      AFG  ...                  NaN                     NaN
3        3      AFG  ...                  NaN                     NaN
4        4      AFG  ...                  NaN                     NaN
..     ...      ...  ...                  ...                     ...
954    955      AUS  ...                  NaN                     NaN
955    956      AUS  ...                  NaN                     NaN
956    957      AUS  ...                  NaN                     NaN
957    958      AUS  ...                  NaN                     NaN
958    959      AUS  ...                  NaN                     NaN

[959 rows x 123 columns]

In [ ]:
## Filter the data based on year

year_data = world_power_data[(world_power_data['year']>2020)]

## Exploratory data analysis

Using housse price dataset

To be continued next session